apiVersion: v1
kind: Service
metadata:
  name: flair-ner-local
spec:
  selector:
    pod: flair-ner-local
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flair-ner-local-up
  namespace: default
data:
  prod_up: |-
    uvicorn jaseci_kit.ent_ext:serv_actions --host 0.0.0.0 --port 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flair-ner-local
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: flair-ner-local
  template:
    metadata:
      labels:
        pod: flair-ner-local
      name: flair-ner-local
    spec:
      nodeSelector:
        node-network: clarity3
      containers:
        - name: flair-ner-local
          imagePullPolicy: Always
          image: daynauth/jaseci-kit:latest 
          resources:
            requests:
              memory: "100Mi"
          command: [bash, -c, "source script/prod_up"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: prod-script
              mountPath: /script

      volumes:
        - name: prod-script
          configMap:
            name: flair-ner-local-up
