apiVersion: v1
kind: Service
metadata:
  name: summarization-local
spec:
  selector:
    pod: summarization-local
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: summarization-local-up
  namespace: default
data:
  prod_up: |-
    cd /jaseci/jaseci_kit/jaseci_kit/modules/summarization
    uvicorn summarization:serv_actions --host 0.0.0.0 --port 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: summarization-local
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: summarization-local
  template:
    metadata:
      labels:
        pod: summarization-local
      name: summarization-local
    spec:
      nodeSelector:
        node-network: clarity3
      containers:
        - name: summarization-local
          imagePullPolicy: IfNotPresent
          image: daynauth/jaseci-kit:latest
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "2Gi"
          command: [bash, -c, "source script/prod_up"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: prod-script
              mountPath: /script

      volumes:
        - name: prod-script
          configMap:
            name: summarization-local-up
