apiVersion: v1
kind: Service
metadata:
  name: bi-enc
spec:
  selector:
    pod: bi-enc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bi-enc-up
  namespace: default
data:
  prod_up: |-
    cd jaseci/jaseci_kit && sh install.sh
    uvicorn jaseci_kit.bi_enc:serv_actions --host 0.0.0.0 --port 80 --workers 1
---
apiVersion: apps/v1
kind: Deployment
metadata: #/usr/local/lib/python3.8/dist-packages
  name: bi-enc
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: bi-enc
  template:
    metadata:
      labels:
        pod: bi-enc
      name: bi-enc
    spec:
      nodeSelector:
        node-network: clarity2
      containers:
        - name: bi-enc
          imagePullPolicy: Always
          image: daynauth/bi_enc:latest
          env: 
          - name: TRANSFORMERS_OFFLINE
            value: "1"
          resources:
            requests:
              memory: "2Gi"
          command: [bash, -c, "source script/prod_up"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: prod-script
              mountPath: /script
      volumes:
        - name: prod-script
          configMap:
            name: bi-enc-up
