apiVersion: v1
kind: Service
metadata:
  name: flair-ner
spec:
  selector:
    pod: flair-ner
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flair-ner-up
  namespace: default
data:
  prod_up: |-
    uvicorn jaseci_kit.ent_ext:serv_actions --host 0.0.0.0 --port 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flair-ner
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: flair-ner
  template:
    metadata:
      labels:
        pod: flair-ner
      name: flair-ner
    spec:
      nodeSelector:
        node-network: clarity2
      containers:
        - name: flair-ner
          imagePullPolicy: IfNotPresent
          image: daynauth/flair:latest 
          env: 
          - name: TRANSFORMERS_OFFLINE
            value: "1"
          resources:
            requests:
              memory: "500Mi"
          command: [bash, -c, "source script/prod_up"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: prod-script
              mountPath: /script

      volumes:
        - name: prod-script
          configMap:
            name: flair-ner-up
