apiVersion: v1
kind: Service
metadata:
  name: pdf-extractor
spec:
  selector:
    pod: pdf-extractor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pdf-extractor-up
  namespace: default
data:
  prod_up: |-
    cd /jaseci/jaseci_kit/jaseci_kit/modules/pdf_extractor
    uvicorn extractor:serv_actions --host 0.0.0.0 --port 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-extractor
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: pdf-extractor
  template:
    metadata:
      labels:
        pod: pdf-extractor
      name: pdf-extractor
    spec:
      nodeSelector:
        node-network: clarity2
      containers:
        - name: pdf-extractor
          image: daynauth/jaseci-full:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "500Mi"
          command: [bash, -c, "source script/prod_up"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: prod-script
              mountPath: /script

      volumes:
        - name: prod-script
          configMap:
            name: pdf-extractor-up
