apiVersion: v1
kind: Service
metadata:
  name: summarization
spec:
  selector:
    pod: summarization
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: summarization-up
  namespace: default
data:
  prod_up: |-
    cd /jaseci/jaseci_kit/jaseci_kit/modules/summarization
    uvicorn summarization:serv_actions --host 0.0.0.0 --port 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: summarization
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: summarization
  template:
    metadata:
      labels:
        pod: summarization
      name: summarization
    spec:
      nodeSelector:
        node-network: clarity2
      containers:
        - name: summarization
          imagePullPolicy: IfNotPresent
          image: daynauth/summarization:latest
          resources:
            requests:
              memory: "2Gi"
          command: [bash, -c, "source script/prod_up"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: prod-script
              mountPath: /script
      volumes:
        - name: prod-script
          configMap:
            name: summarization-up
